-- MySQL Script generated by MySQL Workbench
-- qua 07 abr 2021 16:43:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 3800532_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 3800532_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `3800532_library` ;
USE `3800532_library` ;

-- -----------------------------------------------------
-- Table `3800532_library`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`eixo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`eixo` (
  `ideixo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideixo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`curso` (
  `idcurso` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `eixo_ideixo` INT NOT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `eixo_ideixo_idx` (`eixo_ideixo` ASC),
  CONSTRAINT `eixo_ideixo`
    FOREIGN KEY (`eixo_ideixo`)
    REFERENCES `3800532_library`.`eixo` (`ideixo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(36) NOT NULL,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `tipo_usuario_idtipo_usuario_idx` (`tipo_usuario_idtipo_usuario` ASC),
  INDEX `curso_idcurso_idx` (`curso_idcurso` ASC),
  CONSTRAINT `tipo_usuario_idtipo_usuario`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `3800532_library`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `curso_idcurso`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `3800532_library`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`trabalho` (
  `idtrabalho` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `nropaginas` INT NOT NULL,
  `resumo` LONGTEXT NOT NULL,
  `orientador` VARCHAR(100) NOT NULL,
  `coorientador` VARCHAR(100) NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtrabalho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`autor` (
  `usuario_idusuario` INT NOT NULL,
  `trabalho_idtrabalho` INT NOT NULL,
  INDEX `fk_usuario_has_trabalho_trabalho1_idx` (`trabalho_idtrabalho` ASC),
  INDEX `fk_usuario_has_trabalho_usuario1_idx` (`usuario_idusuario` ASC),
  PRIMARY KEY (`usuario_idusuario`, `trabalho_idtrabalho`),
  CONSTRAINT `fk_usuario_has_trabalho_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `3800532_library`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_trabalho_trabalho1`
    FOREIGN KEY (`trabalho_idtrabalho`)
    REFERENCES `3800532_library`.`trabalho` (`idtrabalho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3800532_library`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3800532_library`.`historico` (
  `idhistorico` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `trabalho_idtrabalho` INT NOT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `usuario_idusuario_idx` (`usuario_idusuario` ASC),
  INDEX `trabalho_idtrabalho_idx` (`trabalho_idtrabalho` ASC),
  CONSTRAINT `usuario_idusuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `3800532_library`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `trabalho_idtrabalho`
    FOREIGN KEY (`trabalho_idtrabalho`)
    REFERENCES `3800532_library`.`trabalho` (`idtrabalho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
